---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
library(tidyverse)
library(lubridate)
library(here)
```

```{r}
species<- read.csv(here( "Data", "maggie_clean_species.csv"))
```


is there a difference in number of species detected between phase and treatment
can ask for how to make graph and stat test

need for statistic test for num species

```{r}
num_species<- species %>% group_by(Cam_SD, Phase, Treatment) %>% summarise(
  num_species = length(unique(choice))
)
```

now run stats
ANOVA 2way w interaction
```{r}
mspecies<- aov(num_species~ Phase + Treatment + Phase*Treatment, data = num_species)
summary(mspecies)
anova(mspecies)
```



for plotting need average 
T = true na.rm for saying to ignore NA
```{r}
avg_species<- num_species %>% group_by(Phase, Treatment) %>% summarise(
  avg_species = mean(num_species, na.rm = T), 
  sd_species = sd(num_species, na.rm = T)
)
```

now plot the data
+ creates new layer
```{r}
ggplot(avg_species, aes(Treatment, avg_species, group =Phase, color = Phase)) + 
  geom_line()+
  geom_point()+
  geom_errorbar(ymin = avg_species- sd_species, ymax = avg_species + sd_species)
```
